apiVersion: 1
datasources:
  - name: influxdb
    type: influxdb
    access: proxy
    database: sensors
    user: ""
    password: ""
    url: http://influxdb:8086
    isDefault: true
    editable: true
 